development:
  adapter: redis
  url: <%= ENV.fetch("CACHE_URL"){ "redis://localhost:6379/1" } %>
  channel_prefix: simple-mm_development

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("CACHE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: simple-mm_production
