AllCops:
  Exclude:
    - bin/*
    - db/*


Layout/LineLength:
  Max: 120
  Exclude:
    - db/**/*
    - spec/**/*
    - features/**/*
    - lib/tasks/**/*
  IgnoredPatterns:
    - '\s*#\s.*'

Metrics/BlockLength:
  Max: 50
  Exclude:
    - db/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 50
  Exclude:
    - db/**/*
    - spec/**/*

Layout/LineLength:
  Max: 160
  Exclude:
    - db/**/*
    - lib/tasks/*

Lint/SuppressedException:
  Exclude:
    - config/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false