AllCops:
  Exclude:
    - bin/*
    - db/*

Metrics/BlockLength:
  Max: 50
  Exclude:
    - db/**/*
    - spec/**/*

Metrics/MethodLength:
  Max: 50
  Exclude:
    - db/**/*
    - spec/**/*

Layout/LineLength:
  Max: 160
  Exclude:
    - db/**/*
    - spec/**/*
    - features/**/*
    - lib/tasks/**/*

Lint/SuppressedException:
  Exclude:
    - config/*

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false