source 'https://rubygems.org'

ruby '3.1.2'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 7.0.0'

# Rails admin for simple admin interface
gem 'rails_admin', '~>3.0'
gem 'sprockets-rails', '>= 3.4.2'
gem "sassc-rails"

# Carrierwave to handle image uploads
gem 'carrierwave', '~> 2.0'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
gem 'redis', '~> 4.5.1'
# Use ActiveModel has_secure_password
gem 'bcrypt', '~> 3.1.12'

# Use ActiveStorage variant
gem 'mini_magick', '~> 4.8'

# We use AASM for managing state in stateful models.
gem 'aasm', '~> 5.2.0'

# Using this for authentication for server-client connection.
gem 'jwt'

# We'll always be using CORS
gem 'rack-cors'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# I'm going to enforce the default style for more consistent file organization
gem 'rubocop', '~> 0.79.0'

# We're running postgres for all environments, since everything is dockerized.
gem 'pg', '>= 1.2.2'

# We're also _always_ using unicorn & sidekiq with a redis instance (as it's dockerized)
gem 'unicorn', '~> 6.0.0'
gem 'sidekiq', '>= 6.0.4'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

group :development, :test do
  # Pry is better than byebug :)
  gem 'pry', '~> 0.12.2'
  gem 'pry-nav'
  gem 'annotate'

  # Explicitly testing libraries
  gem 'rspec-rails'
  gem 'factory_bot'
  gem 'factory_bot_rails'
  gem 'faker'
end

group :development do
  # For barebones development
  gem "puma", "~> 5.5"
  # Access an interactive console on exception pages or by calling 'console' anywhere in the code.
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'web-console', '>= 3.3.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

group :test do
  # Adds support for Capybara system testing and selenium driver
  gem 'capybara', '>= 2.15'
  gem 'selenium-webdriver'
  # Easy installation and use of chromedriver to run system tests with Chrome
  gem 'chromedriver-helper'
end

# Using only certain parts of devise, specifically their entire 
# forgotten password flow & user authentication, might expand to using permissions.
gem "devise"
